### ISSUE TITLE
Compiled binaries ? - doesn't compile in vs2012

### ISSUE THREAD

**Issue by mikerg87** [stevedesmond-ca/LoadTestToolbox#11]
Could we get compiled binaries. I can't compile this in vs2012. I guess there are new language features in use that aren't available to 2012.

**Comment by stevedesmond-ca** [comment]
Sure thing, I'll see if I have time this weekend.

**Comment by mikerg87** [comment]
Great. The project intrigues me - what version of VS should I have if I want to make a contribution?

**Comment by stevedesmond-ca** [comment]
I believe 2015 and Code are the only ones that support .NET 4.6 -- both are free at VisualStudio.com

**Comment by stevedesmond-ca** [comment]
[LoadTestToolbox.zip](https://github.com/stevedesmond-ca/LoadTestToolbox/files/139860/LoadTestToolbox.zip)
