### ISSUE TITLE
Authenitcation capabilities?

### ISSUE THREAD

**Issue by mikerg87** [stevedesmond-ca/LoadTestToolbox#13]
A lot of the time, I need to be able to issue a cookie or somehow supply auth credentials so that I can load test resources that are secure.

**Comment by stevedesmond-ca** [comment]
If you're talking HTTP basic authentication, you can use the URL format http://user:pass@example.com/page

If you're talking about something like POSTing to the server, it's in my mental roadmap to support scripts to run through instead of a single URL

**Comment by mikerg87** [comment]
very well

**Comment by stevedesmond-ca** [comment]
Closing this, as it will be covered by #18
