### ISSUE TITLE
Incorrect response time in output and chart?

### ISSUE THREAD

**Issue by kristofferjansson** [stevedesmond-ca/LoadTestToolbox#15]
The calculated response time seems wrong if the intention is to present in milliseconds.
Several tests against urls that I know takes longer than LoadTestToolbox presented makes me think that the calculation of elapsed time is the problem.

**Comment by stevedesmond-ca** [comment]
Resolved by #16

**Comment by stevedesmond-ca** [comment]
For the record, the times you are seeing are server response times for the initial request, which can be drastically different from browser rendering times

The other thing to make sure is that you're specifying the protocol (`http://example.com` vs just `example.com`)
