### ISSUE TITLE
Use DateTime.UtcNow when time zone doesn't matter

### ISSUE THREAD

**Issue by bernhard-hofmann** [stevedesmond-ca/LoadTestToolbox#5]
`DateTime.UtcNow` is 3.3 times faster than `DateTime.Now` [reference](http://www.thearchitect.co.uk/weblog/archives/2011/08/performance_datetimeutcnow_vs_datetimenow.html).

In places where the time is used to measure elapsed time, `UtcNow` should be used to make it more efficient.

**Comment by stevedesmond-ca** [comment]
Wow, my testing actually shows it as ~100x -- thanks!
